version: "2.3"

services:
  django:
    runtime: nvidia
    environment:
            - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: python manage.py runserver 0.0.0.0:9000
    volumes:        
      - /data:/data




