version: "2.3"

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: python /backend/manage.py runserver 0.0.0.0:9000
    volumes:        
      - /data:/data
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]


            # opencv:
            #         
            #         #    runtime: nvidia
            #         #  environment:
            #         #  - NVIDIA_VISIBLE_DEVICES=all
            #   build:
            #     context: ./mask-rcnn
            #     dockerfile: Dockerfile
            #   ports:
            #     - "10000:10000"
            #   command: python /opencv/mask.py
            #   volumes:
            #     - /data:/data
            #   deploy:
            #     resources:
            #       reservations:
            #         devices:
            #         - capabilities: [gpu]
